Repository pknu-wap/GLOG, pull requests merged in 2023-09, with the labels that each got.

#11 Library 및 기초 세팅
  client/.eslintrc.json
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/api/collect-api.ts
  client/src/api/index.ts
  client/src/app/collect/page.tsx
  client/src/app/globals.css
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/app/posts/Posts.tsx
  client/src/app/posts/getPosts.ts
  client/src/app/posts/hydratedPosts.tsx
  client/src/app/posts/page.tsx
  client/src/components/Layout/Footer.tsx
  client/src/components/Layout/FullLayout.module.css
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/footer.module.css
  client/src/components/Layout/header.module.css
  client/src/components/ReactQuery/Provider.tsx
  client/src/components/ReactQuery/ThemeRegistry.tsx
  client/src/components/ReactQuery/getQueryClient.tsx
  client/src/components/ReactQuery/hydrateOnClient.tsx
  client/src/components/Recoil/Recoil.tsx
  client/src/constant/common.ts
  client/src/recoil/atom.tsx
  client/src/themes/DarkTheme.ts
  client/src/themes/LightTheme.ts
  client/src/themes/color.ts
  client/src/types/common.ts
  client/src/types/dto.ts
Labels: chore

#14 server commit
  server/.gitignore
  server/build.gradle
  server/gradle/wrapper/gradle-wrapper.jar
  server/gradle/wrapper/gradle-wrapper.properties
  server/gradlew
  server/gradlew.bat
  server/settings.gradle
  server/src/main/java/com/project/Glog/GlogApplication.java
  server/src/main/java/com/project/Glog/config/AppProperties.java
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/config/WebMvcConfig.java
  server/src/main/java/com/project/Glog/controller/AuthController.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/domain/AuthProvider.java
  server/src/main/java/com/project/Glog/domain/Blog.java
  server/src/main/java/com/project/Glog/domain/Category.java
  server/src/main/java/com/project/Glog/domain/Post.java
  server/src/main/java/com/project/Glog/domain/User.java
  server/src/main/java/com/project/Glog/dto/ApiResponse.java
  server/src/main/java/com/project/Glog/dto/AuthResponse.java
  server/src/main/java/com/project/Glog/dto/LoginRequest.java
  server/src/main/java/com/project/Glog/dto/PostPreviewDto.java
  server/src/main/java/com/project/Glog/dto/PostPreviewDtos.java
  server/src/main/java/com/project/Glog/dto/SignUpRequest.java
  server/src/main/java/com/project/Glog/dto/request/post/PostCreateRequest.java
  server/src/main/java/com/project/Glog/dto/request/post/PostUpdateRequest.java
  server/src/main/java/com/project/Glog/dto/responsee/post/PostPreviewResponse.java
  server/src/main/java/com/project/Glog/dto/responsee/post/PostReadResponse.java
  server/src/main/java/com/project/Glog/exception/BadRequestException.java
  server/src/main/java/com/project/Glog/exception/OAuth2AuthenticationProcessingException.java
  server/src/main/java/com/project/Glog/exception/ResourceNotFoundException.java
  server/src/main/java/com/project/Glog/repository/BlogRepository.java
  server/src/main/java/com/project/Glog/repository/CategoryRepository.java
  server/src/main/java/com/project/Glog/repository/PostRepository.java
  server/src/main/java/com/project/Glog/repository/UserRepository.java
  server/src/main/java/com/project/Glog/security/CurrentUser.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
  server/src/main/java/com/project/Glog/security/RestAuthenticationEntryPoint.java
  server/src/main/java/com/project/Glog/security/TokenAuthenticationFilter.java
  server/src/main/java/com/project/Glog/security/TokenProvider.java
  server/src/main/java/com/project/Glog/security/UserPrincipal.java
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/project/Glog/security/oauth2/HttpCookieOAuth2AuthorizationRequestRepository.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationFailureHandler.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/com/project/Glog/security/oauth2/user/FacebookOAuth2UserInfo.java
  server/src/main/java/com/project/Glog/security/oauth2/user/GithubEmailInfo.java
  server/src/main/java/com/project/Glog/security/oauth2/user/GithubOAuth2UserInfo.java
  server/src/main/java/com/project/Glog/security/oauth2/user/GoogleOAuth2UserInfo.java
  server/src/main/java/com/project/Glog/security/oauth2/user/OAuth2UserInfo.java
  server/src/main/java/com/project/Glog/security/oauth2/user/OAuth2UserInfoFactory.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/java/com/project/Glog/util/CookieUtils.java
  server/src/test/java/com/project/Glog/GlogApplicationTests.java
Labels: 두영, 백엔드, develop

#15 Chore/#14 프로젝트명변경
  server/settings.gradle
Labels: 백엔드, chore

#22 Feature/#18 blog api
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/dto/responsee/blog/MyPageResponse.java
  server/src/main/java/com/project/Glog/dto/responsee/post/PostPreviewDto.java
  server/src/main/java/com/project/Glog/dto/responsee/post/PostPreviewDtos.java
  server/src/main/java/com/project/Glog/dto/responsee/post/PostPreviewResponse.java
  server/src/main/java/com/project/Glog/exception/BadRequestException.java
  server/src/main/java/com/project/Glog/service/BlogService.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 두영, 백엔드, feature, modify

#24 #19 카테고리 기능 추가
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/controller/CategoryController.java
  server/src/main/java/com/project/Glog/dto/PostTitleDto.java
  server/src/main/java/com/project/Glog/dto/responsee/category/SidebarDto.java
  server/src/main/java/com/project/Glog/dto/responsee/category/SidebarDtos.java
  server/src/main/java/com/project/Glog/service/CategoryService.java
Labels: 두영, 백엔드, feature

#25 #23 유저 정보 수정 기능 추가
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/domain/User.java
  server/src/main/java/com/project/Glog/dto/request/user/UserInfoChangeRequest.java
  server/src/main/java/com/project/Glog/dto/responsee/user/UserDto.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
Labels: 두영, 백엔드, feature, modify

#26 Swagger추가
  server/build.gradle
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
Labels: 두영, 백엔드, feature, docs, chore

#28 ✨ Feature/#20 이미지 기능
  server/build.gradle
  server/src/main/java/com/project/Glog/config/AwsS3Config.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/dto/AwsS3.java
  server/src/main/java/com/project/Glog/dto/request/post/PostCreateRequest.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/java/com/project/Glog/util/AwsUtils.java
Labels: 두영, 백엔드, feature

#46 ✨#38 도메인(도연)
  server/src/main/java/com/project/Glog/domain/BookMessage.java
  server/src/main/java/com/project/Glog/domain/Friend.java
  server/src/main/java/com/project/Glog/domain/GuestBook.java
  server/src/main/java/com/project/Glog/domain/History.java
  server/src/main/java/com/project/Glog/domain/Template.java
  server/src/main/java/com/project/Glog/domain/TemplateHashtag.java
  server/src/main/java/com/project/Glog/domain/Temporary.java
  server/src/main/java/com/project/Glog/domain/TemporaryHashtag.java
  server/src/main/java/com/project/Glog/domain/User.java
Labels: 도연, 백엔드, feature

#47 Feature/#44 ✨스크랩 마무리
  client/src/app/scrap/Post/Post.style.tsx
  client/src/app/scrap/Post/Post.tsx
  client/src/app/scrap/Post/Post.type.tsx
  client/src/app/scrap/page.tsx
  client/src/app/scrap/scrap.style.tsx
  client/src/components/Post/Post.style.tsx
  client/src/components/Post/Post.tsx
  client/src/components/Post/Post.type.tsx
  client/src/themes/DarkTheme.ts
  client/src/themes/LightTheme.ts
Labels: 준서, 프론트엔드, feature
