Repository pknu-wap/GLOG, pull requests merged in 2023-10, with the labels that each got.

#49 🎨스크랩페이지 오류 수정
  client/src/app/[titleId]/page.tsx
  client/src/app/scrap/page.tsx
  client/src/app/scrap/scrap.style.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Post/Post.style.tsx
  client/src/components/Post/Post.tsx
  client/src/components/Sidebar/Sidebar.styles.tsx
  client/src/themes/DarkTheme.ts
  client/src/themes/LightTheme.ts
Labels: 준서, fix, 프론트엔드

#51 ✨ 글쓰기 페이지 구현
  client/next.config.js
  client/package-lock.json
  client/package.json
  client/src/app/[titleId]/[postId]/page.tsx
  client/src/app/layout.tsx
  client/src/app/page.tsx
  client/src/app/scrap/page.tsx
  client/src/app/scrap/scrap.style.tsx
  client/src/app/write/Bottom/BottomButton.tsx
  client/src/app/write/Bottom/SaveDialog.tsx
  client/src/app/write/Modal/SaveModal.style.tsx
  client/src/app/write/Modal/SaveModal.tsx
  client/src/app/write/Modal/TempSaveModal.tsx
  client/src/app/write/Modal/TemplateModal.tsx
  client/src/app/write/TagList.tsx
  client/src/app/write/Top/TopButton.tsx
  client/src/app/write/Write.style.tsx
  client/src/app/write/page.tsx
  client/src/components/Dialog/Dialog.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/List/List.tsx
  client/src/components/Modal/Modal.style.tsx
  client/src/components/Modal/Modal.tsx
  client/src/components/Modal/ModalButton.tsx
  client/src/components/Sidebar/Sidebar.tsx
  client/src/types/common.ts
Labels: 채연, 프론트엔드, feature

#53 Feature/#39 댓글
  server/src/main/java/com/project/Glog/controller/AuthController.java
  server/src/main/java/com/project/Glog/controller/ReplyController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/domain/Post.java
  server/src/main/java/com/project/Glog/domain/Reply.java
  server/src/main/java/com/project/Glog/dto/ApiResponse.java
  server/src/main/java/com/project/Glog/dto/AuthResponse.java
  server/src/main/java/com/project/Glog/dto/LoginRequest.java
  server/src/main/java/com/project/Glog/dto/ReplyDto.java
  server/src/main/java/com/project/Glog/dto/SignUpRequest.java
  server/src/main/java/com/project/Glog/dto/UserDto.java
  server/src/main/java/com/project/Glog/dto/request/post/PostCreateRequest.java
  server/src/main/java/com/project/Glog/dto/request/reply/ReplyCreateRequest.java
  server/src/main/java/com/project/Glog/dto/request/reply/ReplyGetRequest.java
  server/src/main/java/com/project/Glog/dto/request/reply/ReplyUpdateRequest.java
  server/src/main/java/com/project/Glog/dto/responsee/reply/ReplyGetResponse.java
  server/src/main/java/com/project/Glog/dto/responsee/user/UserDetailResponse.java
  server/src/main/java/com/project/Glog/exception/BadRequestException.java
  server/src/main/java/com/project/Glog/repository/ReplyRepository.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
  server/src/main/java/com/project/Glog/security/UserPrincipal.java
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
Labels: 두영, feature, modify

#55 ✨Feature/#54 블로그 생성
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/dto/request/user/UserCreateRequest.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
  server/src/main/java/com/project/Glog/security/UserPrincipal.java
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/project/Glog/service/BlogService.java
Labels: 도연, 백엔드, feature

#56 ✨Feature/#40 좋아요
  server/src/main/java/com/project/Glog/controller/ReplyController.java
  server/src/main/java/com/project/Glog/repository/PostLikeRepository.java
  server/src/main/java/com/project/Glog/repository/ReplyLikeRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
Labels: 도연, 백엔드, feature

#58 #40 repository 메서드 수정
  server/src/main/java/com/project/Glog/repository/ReplyLikeRepository.java
Labels: 두영, 백엔드, refactor

#62 #61 thumbnail null 허용
  server/src/main/java/com/project/Glog/GlogApplication.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/domain/Post.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 두영, 백엔드, feature, modify

#63 ✨댓글 기능 추가
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/controller/CategoryController.java
  server/src/main/java/com/project/Glog/controller/ReplyController.java
  server/src/main/java/com/project/Glog/dto/request/reply/ReplyGetRequest.java
  server/src/main/java/com/project/Glog/repository/ReplyRepository.java
  server/src/main/java/com/project/Glog/service/CategoryService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
Labels: 두영, 백엔드, feature

#65 Feature/#50 ✨카테고리별 페이지 구현 2
  client/src/app/[titleId]/page.tsx
  client/src/app/[titleId]/tagegory.style.tsx
  client/src/app/scrap/page.tsx
  client/src/components/DND/DragANdDrop.style.tsx
  client/src/components/DND/DragAndDrop.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Post/Post.tsx
  client/src/components/Sidebar/Sidebar.tsx
Labels: 준서, 프론트엔드, feature

#66 ✨ 스크랩 생성
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/controller/ScrapController.java
  server/src/main/java/com/project/Glog/domain/Scrap.java
  server/src/main/java/com/project/Glog/dto/PostPreviewDto.java
  server/src/main/java/com/project/Glog/dto/PostPreviewDtos.java
  server/src/main/java/com/project/Glog/dto/response/post/PostPreviewResponse.java
  server/src/main/java/com/project/Glog/repository/ScrapRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/java/com/project/Glog/service/ScrapService.java
Labels: 두영, 백엔드, feature, modify

#68 🐛 글쓰기 페이지 UI 수정 및 전체 페이지 버그 수정
  client/.gitignore
  client/hooks/useRecoilSSR.ts
  client/src/api/index.ts
  client/src/app/globals.css
  client/src/app/write/[categoryId]/[postId]/page.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Modal/ModalButton.tsx
  client/src/components/ReactQuery/ThemeRegistry.tsx
  client/src/recoil/atom.tsx
Labels: 채연, fix, 프론트엔드

#71 ✨게시물 페이지 구현
  client/src/app/[titleId]/[postId]/page.tsx
  client/src/app/home/[titleId]/[postId]/page.tsx
  client/src/app/home/[titleId]/[postId]/postId.style.tsx
  client/src/app/home/[titleId]/page.tsx
  client/src/app/home/[titleId]/tagegory.style.tsx
  client/src/components/DND/DragAndDrop.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Sidebar/Sidebar.styles.tsx
  client/src/themes/DarkTheme.ts
Labels: 준서, 프론트엔드, feature

#78 ✨Feature/#72 템플릿
  server/src/main/java/com/project/Glog/config/AppProperties.java
  server/src/main/java/com/project/Glog/controller/TemplateController.java
  server/src/main/java/com/project/Glog/domain/Template.java
  server/src/main/java/com/project/Glog/domain/TemplateTemporary.java
  server/src/main/java/com/project/Glog/domain/Temporary.java
  server/src/main/java/com/project/Glog/domain/TemporaryHashtag.java
  server/src/main/java/com/project/Glog/dto/PostBasicDto.java
  server/src/main/java/com/project/Glog/dto/response/post/PostTitleDto.java
  server/src/main/java/com/project/Glog/dto/response/post/PostTitleResponse.java
  server/src/main/java/com/project/Glog/repository/PostHashtagRepository.java
  server/src/main/java/com/project/Glog/repository/TemplateHashtagRepository.java
  server/src/main/java/com/project/Glog/repository/TemplateRepository.java
  server/src/main/java/com/project/Glog/repository/TemporaryHashtagRepository.java
  server/src/main/java/com/project/Glog/security/TokenProvider.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/com/project/Glog/service/TemplateService.java
  server/src/main/java/com/project/Glog/service/TemporaryService.java
Labels: 도연, 백엔드, feature

#85 Feature/#80 ✨친구목록 구현
  client/src/components/Layout/Header.style.tsx
  client/src/components/Layout/Header.tsx
Labels: 준서, 프론트엔드, feature
