Repository pknu-wap/GLOG, pull requests merged in 2023-11, with the labels that each got.

#87 Feature/#74 방명록 서버
  server/src/main/java/com/project/Glog/controller/GuestbookController.java
  server/src/main/java/com/project/Glog/domain/Blog.java
  server/src/main/java/com/project/Glog/domain/BookMessage.java
  server/src/main/java/com/project/Glog/domain/Guestbook.java
  server/src/main/java/com/project/Glog/domain/User.java
  server/src/main/java/com/project/Glog/dto/MessageDto.java
  server/src/main/java/com/project/Glog/dto/UserDto.java
  server/src/main/java/com/project/Glog/dto/request/guestbook/GuestbookMessageRequest.java
  server/src/main/java/com/project/Glog/dto/response/guestbook/GuestbookResponse.java
  server/src/main/java/com/project/Glog/repository/BookMessageRepository.java
  server/src/main/java/com/project/Glog/repository/GuestbookRepository.java
  server/src/main/java/com/project/Glog/service/BlogService.java
  server/src/main/java/com/project/Glog/service/GuestbookService.java
  server/src/main/resources/data.sql
Labels: 두영, 백엔드, feature

#93 ✨Feature/#92 리드미
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/service/BlogService.java
  server/src/main/resources/data.sql
Labels: 도연, 백엔드, feature

#95 발자국 연간 기준 단계 추가
  server/src/main/java/com/project/Glog/domain/History.java
  server/src/main/java/com/project/Glog/dto/response/history/Year.java
  server/src/main/java/com/project/Glog/repository/HistoryRepository.java
  server/src/main/java/com/project/Glog/service/HistoryService.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/resources/data.sql
Labels: 종경, 백엔드, feature

#98 prpostresponse 구현
  server/src/main/java/com/project/Glog/controller/PrPostController.java
  server/src/main/java/com/project/Glog/dto/response/pr/PrPostResponse.java
  server/src/main/java/com/project/Glog/dto/response/pr/PrPostedDto.java
  server/src/main/java/com/project/Glog/dto/response/pr/PrPostedDtos.java
  server/src/main/java/com/project/Glog/repository/CategoryRepository.java
  server/src/main/java/com/project/Glog/repository/PrPostRepository.java
  server/src/main/java/com/project/Glog/service/PrPostService.java
  server/src/main/resources/data.sql
Labels: 종경, 백엔드, feature

#100 🎨 router.push -> Link 태그로 변경하기
  client/src/components/DND/DragAndDrop.tsx
  client/src/components/FootPrint/FootPrint.style.tsx
  client/src/components/Layout/CenterContent.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/PageLink/PageLink.tsx
  client/src/components/Post/Post.style.tsx
  client/src/components/Sidebar/SidebarSubMenuContainer.tsx
  client/src/themes/DarkTheme.ts
  client/src/themes/LightTheme.ts
Labels: 채연, fix, 프론트엔드, refactor

#103 Feature/#102 검색 서버
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/repository/PostHashtagRepository.java
  server/src/main/java/com/project/Glog/repository/PostRepository.java
  server/src/main/java/com/project/Glog/repository/UserRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 두영, 백엔드, feature

#105 발자국 기능 코드 수정
  server/src/main/java/com/project/Glog/dto/response/history/Week.java
  server/src/main/java/com/project/Glog/service/HistoryService.java
Labels: 종경, fix, 백엔드, refactor

#111 ✨스크롤UI커스텀 및 전역선언
  client/src/app/globals.css
Labels: 준서, 프론트엔드, feature

#115 깃허브 토큰 업데이트
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
Labels: 종경, 백엔드, modify

#113 Feature/#110 카테고리 서버
  server/src/main/java/com/project/Glog/controller/CategoryController.java
  server/src/main/java/com/project/Glog/dto/request/category/CategoryUpdateRequest.java
  server/src/main/java/com/project/Glog/dto/response/category/CategoryDto.java
  server/src/main/java/com/project/Glog/service/CategoryService.java
Labels: 두영, 백엔드, feature

#119 블로그url -> 블로그Id api 추가
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/repository/BlogRepository.java
  server/src/main/java/com/project/Glog/service/BlogService.java
Labels: 종경, 백엔드, feature

#120 ✨ 템플릿 페이지 API 연동
  client/hooks/useRecoilSSR.ts
  client/src/api/write-api.ts
  client/src/app/[blogName]/scrap/page.tsx
  client/src/app/oauth2/redirect/page.tsx
  client/src/app/write/TagList.tsx
  client/src/app/write/Top/TopButton.tsx
  client/src/app/write/[categoryId]/[postId]/Bottom/BottomButton.tsx
  client/src/app/write/[categoryId]/[postId]/Bottom/SaveDialog.tsx
  client/src/app/write/[categoryId]/[postId]/Modal/SaveModal.tsx
  client/src/app/write/[categoryId]/[postId]/Modal/TemplateModal.tsx
  client/src/app/write/[categoryId]/[postId]/page.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/PhoneType/PhoneType.tsx
  client/src/constant/common.ts
  client/src/recoil/atom.tsx
  client/src/types/dto.ts
Labels: 채연, 프론트엔드, feature

#121 Feature/#116 리드미 페이지 연동
  client/src/api/blog-api.ts
  client/src/api/readme-api.ts
  client/src/api/reply-api.ts
  client/src/app/[blogName]/home/[categoryId]/[postId]/page.tsx
  client/src/app/[blogName]/home/[categoryId]/[postId]/postId.style.tsx
  client/src/app/[blogName]/page.tsx
  client/src/types/dto.ts
Labels: 준서, 프론트엔드, feature, modify

#126 것허브 api 간단한 리팩토링
  server/src/main/java/com/project/Glog/controller/GitHubController.java
  server/src/main/java/com/project/Glog/repository/GithubRepoRepository.java
  server/src/main/java/com/project/Glog/service/GitHubService.java
Labels: 종경, 백엔드, refactor

#122 ✨Feature/#106 친구 기능 구현
  server/src/main/java/com/project/Glog/controller/FriendController.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/domain/Friend.java
  server/src/main/java/com/project/Glog/domain/User.java
  server/src/main/java/com/project/Glog/dto/UserSimpleDto.java
  server/src/main/java/com/project/Glog/dto/UserSimpleDtos.java
  server/src/main/java/com/project/Glog/dto/response/user/UserFriendResponse.java
  server/src/main/java/com/project/Glog/dto/response/user/UserModalResponse.java
  server/src/main/java/com/project/Glog/repository/FriendRepository.java
  server/src/main/java/com/project/Glog/repository/UserRepository.java
  server/src/main/java/com/project/Glog/service/FriendService.java
Labels: 도연, 백엔드, feature

#128 Feature/#123 알람
  server/build.gradle
  server/src/main/java/com/project/Glog/config/SwaggerConfig.java
  server/src/main/java/com/project/Glog/controller/AlarmController.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/controller/ReplyController.java
  server/src/main/java/com/project/Glog/controller/TemplateController.java
  server/src/main/java/com/project/Glog/controller/TemporaryController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/domain/Alarm.java
  server/src/main/java/com/project/Glog/domain/AlarmType.java
  server/src/main/java/com/project/Glog/domain/User.java
  server/src/main/java/com/project/Glog/dto/AlarmDto.java
  server/src/main/java/com/project/Glog/dto/AlarmDtos.java
  server/src/main/java/com/project/Glog/dto/request/reply/ReplyGetRequest.java
  server/src/main/java/com/project/Glog/repository/AlarmRepository.java
  server/src/main/java/com/project/Glog/service/AlarmService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
  server/src/main/resources/data.sql
Labels: 두영, 백엔드, feature

#131 ✨ 댓글 UI 생성 및 백엔드 연동
  client/src/api/reply-api.ts
  client/src/app/[blogName]/home/[categoryId]/[postId]/page.tsx
  client/src/app/[blogName]/home/[categoryId]/[postId]/postId.style.tsx
  client/src/types/dto.ts
Labels: 준서, fix, 프론트엔드, feature

#136 pr 연동 추가 수정
  server/src/main/java/com/project/Glog/domain/GithubRepository.java
  server/src/main/java/com/project/Glog/domain/Post.java
  server/src/main/java/com/project/Glog/dto/request/post/PostCreateRequest.java
  server/src/main/java/com/project/Glog/service/GitHubService.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/resources/data.sql
Labels: 종경, 백엔드, feature

#137 pr api 간단한 수정
  server/src/main/java/com/project/Glog/controller/GitHubController.java
Labels: 종경, fix, 백엔드

#138 🐛Fix/#133 친구 기능 수정
  server/src/main/java/com/project/Glog/dto/UserSimpleDtos.java
  server/src/main/java/com/project/Glog/dto/response/user/UserFriendResponse.java
  server/src/main/java/com/project/Glog/service/FriendService.java
Labels: 도연, fix, 백엔드

#140 ✨Feature/#139 nickname api
  server/src/main/java/com/project/Glog/controller/FriendController.java
  server/src/main/java/com/project/Glog/service/FriendService.java
Labels: 도연, 백엔드, feature

#141 ✨ 친구 백엔드 연동
  client/src/api/friend-api.ts
  client/src/app/[blogName]/page.tsx
  client/src/components/Layout/Header.style.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModal.style.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModal.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModalMenu.tsx
  client/src/types/dto.ts
Labels: 준서, 프론트엔드, feature, modify

#145 쿼리 수정
  server/src/main/java/com/project/Glog/repository/PostRepository.java
Labels: 두영, fix, 백엔드

#144 ✨ 댓글, 친구모달에서 소개 모달 / 친구 요청
  client/next.config.js
  client/src/api/friend-api.ts
  client/src/api/introduce-api.ts
  client/src/app/[blogName]/home/[categoryId]/[postId]/IntroduceModal/IntroduceModal.tsx
  client/src/app/[blogName]/home/[categoryId]/[postId]/page.tsx
  client/src/app/[blogName]/home/[categoryId]/[postId]/postId.style.tsx
  client/src/app/[blogName]/home/[categoryId]/page.tsx
  client/src/app/collect/CollectPost.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModal.style.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModal.tsx
  client/src/types/dto.ts
Labels: 준서, 프론트엔드, feature

#147 ✨Feature/#129 방문 기록 유입 경로
  .idea/GLOG.iml
  .idea/compiler.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/workspace.xml
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/controller/PathController.java
  server/src/main/java/com/project/Glog/controller/VisitController.java
  server/src/main/java/com/project/Glog/domain/Path.java
  server/src/main/java/com/project/Glog/domain/Visit.java
  server/src/main/java/com/project/Glog/dto/PathDto.java
  server/src/main/java/com/project/Glog/repository/PathRepository.java
  server/src/main/java/com/project/Glog/repository/VisitRepository.java
  server/src/main/java/com/project/Glog/service/PathService.java
  server/src/main/java/com/project/Glog/service/VisitService.java
Labels: 도연, 백엔드, feature

#154 Fix/#152 추가 요구사항
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/dto/PostPreviewDto.java
  server/src/main/java/com/project/Glog/service/BlogService.java
Labels: 두영, fix, 백엔드

#156 ✨ 마이페이지 백엔드 구현
  client/package-lock.json
  client/package.json
  client/src/api/mypage-api.ts
  client/src/app/[blogName]/page.tsx
  client/src/app/[blogName]/prList/[categoryId]/page.tsx
  client/src/app/layout.tsx
  client/src/app/mypage/page.tsx
  client/src/components/Github/.Github.tsx.swp
  client/src/components/Github/Github.tsx
  client/src/constant/common.ts
  client/src/types/dto.ts
Labels: 채연, 프론트엔드, feature

#158 search 수정
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 종경, 백엔드, feature

#160 카테고리 dto 에 isPrPost 추가
  server/src/main/java/com/project/Glog/dto/response/category/SidebarDto.java
Labels: 종경, 백엔드, feature

#159 ✨ 방명록 연동 / 카테고리 연동
  client/src/api/category-api.ts
  client/src/api/guestbook-api.ts
  client/src/api/index.ts
  client/src/api/makeAccount-api.ts
  client/src/api/reply-api.ts
  client/src/api/userDetail-api.ts
  client/src/app/[blogName]/home/[categoryId]/[postId]/page.tsx
  client/src/app/[blogName]/home/[categoryId]/[postId]/postId.style.tsx
  client/src/app/[blogName]/home/[categoryId]/page.tsx
  client/src/app/[blogName]/page.tsx
  client/src/components/DND/CategorySettingModal.tsx
  client/src/components/DND/CreateCategoryModal.tsx
  client/src/components/DND/DragAndDrop.tsx
  client/src/components/FootPrint/FootPrintAnimation.tsx
  client/src/components/Github/Github.tsx
  client/src/components/GuestBook/Comment.tsx
  client/src/components/GuestBook/CommentTime.tsx
  client/src/components/GuestBook/GuestBookModal.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModal.tsx
  client/src/types/common.ts
  client/src/types/dto.ts
Labels: 준서, 프론트엔드, feature, modify

#162 추가적인 수정
  server/src/main/java/com/project/Glog/repository/PostRepository.java
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/project/Glog/service/BlogService.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 종경, 백엔드, feature

#164 get/blog/url 추가
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/repository/BlogRepository.java
  server/src/main/java/com/project/Glog/service/BlogService.java
Labels: 종경, 백엔드, feature

#165 깃허브 레포 수정
  server/src/main/java/com/project/Glog/controller/GitHubController.java
  server/src/main/java/com/project/Glog/domain/GithubRepository.java
  server/src/main/java/com/project/Glog/repository/GithubRepoRepository.java
  server/src/main/java/com/project/Glog/service/GitHubService.java
  server/src/main/resources/data.sql
Labels: 종경, 백엔드, feature

#166 깃허브 수정
  server/src/main/java/com/project/Glog/controller/GitHubController.java
  server/src/main/java/com/project/Glog/repository/GithubRepoRepository.java
Labels: 종경, 백엔드, feature

#167 prPost 작성 시 prid만 받기
  server/src/main/java/com/project/Glog/repository/PrPostRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 종경, 백엔드, feature

#168 찐막
  server/src/main/java/com/project/Glog/dto/PostBasicDto.java
  server/src/main/java/com/project/Glog/service/GuestbookService.java
Labels: 두영, fix, 백엔드

#169 찐막
  server/src/main/java/com/project/Glog/service/GitHubService.java
Labels: 두영, fix, 백엔드

#170 수정
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/repository/PostRepository.java
  server/src/main/java/com/project/Glog/repository/PrPostRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 종경, 백엔드, feature

#171 Fix/찐찐찐막
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/repository/PostRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/resources/data.sql
Labels: 두영, 백엔드, feature

#173 ✨ 미구현 페이지들 구현 및 버그 수정
  client/src/api/blog-api.ts
  client/src/api/category-api.ts
  client/src/api/collect-api.ts
  client/src/api/friend-api.ts
  client/src/api/github-api.ts
  client/src/api/index.ts
  client/src/api/introduce-api.ts
  client/src/api/pr-api.ts
  client/src/api/reply-api.ts
  client/src/api/userDetail-api.ts
  client/src/api/write-api.ts
  client/src/app/[blogName]/home/[categoryId]/[postId]/page.tsx
  client/src/app/[blogName]/home/[categoryId]/[postId]/postId.style.tsx
  client/src/app/[blogName]/prList/[categoryId]/page.tsx
  client/src/app/collect/CollectPost.tsx
  client/src/app/collect/page.tsx
  client/src/app/oauth2/redirect/page.tsx
  client/src/app/register/page.tsx
  client/src/app/scrap/page.tsx
  client/src/app/scrap/scrap.style.tsx
  client/src/app/write/Modal/SaveModal.tsx
  client/src/app/write/pr/update/[categoryId]/[postId]/page.tsx
  client/src/app/write/update/[categoryId]/[postId]/page.tsx
  client/src/components/DND/CategorySettingModal.tsx
  client/src/components/DND/CreateCategoryModal.tsx
  client/src/components/DND/DragAndDrop.tsx
  client/src/components/Github/Github.tsx
  client/src/components/Header/SettingMenu.tsx
  client/src/components/Layout/FullLayout.tsx
  client/src/components/Layout/Header.tsx
  client/src/components/Layout/HeaderFriendModal/FriendModal.tsx
  client/src/components/Post/Post.tsx
  client/src/constant/common.ts
  client/src/types/dto.ts
Labels: 채연, 프론트엔드, feature, modify

#175 댓글 익명 사용자 추가
  server/src/main/java/com/project/Glog/service/ReplyService.java
Labels: 종경, 백엔드, feature

#176 리드미 수정
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/dto/response/blog/ReadMeDto.java
  server/src/main/java/com/project/Glog/repository/BlogRepository.java
  server/src/main/java/com/project/Glog/service/BlogService.java
Labels: 종경, 백엔드, feature

#177 🐛Fix/찐찐찐막
  server/src/main/java/com/project/Glog/repository/PostLikeRepository.java
  server/src/main/java/com/project/Glog/service/PostService.java
Labels: 두영, fix, 백엔드
