Repository pknu-wap/GLOG, pull requests merged in 2024-07, with the labels that each got.

#181 #179-S3 연결
  server/src/main/resources/application.properties
Labels: 종경, 백엔드, chore

#182 #180-알림 기능 수정
  server/src/main/java/com/project/Glog/controller/AlarmController.java
  server/src/main/java/com/project/Glog/domain/Alarm.java
  server/src/main/java/com/project/Glog/domain/AlarmType.java
  server/src/main/java/com/project/Glog/dto/AlarmDto.java
  server/src/main/java/com/project/Glog/service/AlarmService.java
  server/src/main/java/com/project/Glog/service/FriendService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
Labels: 종경, 백엔드, modify

#184 #183-의존성 주입 방법 변경 완료
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/controller/BlogController.java
  server/src/main/java/com/project/Glog/controller/CategoryController.java
  server/src/main/java/com/project/Glog/controller/FriendController.java
  server/src/main/java/com/project/Glog/controller/GitHubController.java
  server/src/main/java/com/project/Glog/controller/GuestbookController.java
  server/src/main/java/com/project/Glog/controller/HistoryController.java
  server/src/main/java/com/project/Glog/controller/ImageController.java
  server/src/main/java/com/project/Glog/controller/PathController.java
  server/src/main/java/com/project/Glog/controller/PostController.java
  server/src/main/java/com/project/Glog/controller/PrPostController.java
  server/src/main/java/com/project/Glog/controller/ReplyController.java
  server/src/main/java/com/project/Glog/controller/ScrapController.java
  server/src/main/java/com/project/Glog/controller/TemplateController.java
  server/src/main/java/com/project/Glog/controller/TemporaryController.java
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/controller/VisitController.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
  server/src/main/java/com/project/Glog/security/TokenAuthenticationFilter.java
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationFailureHandler.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  server/src/main/java/com/project/Glog/service/BlogService.java
  server/src/main/java/com/project/Glog/service/CategoryService.java
  server/src/main/java/com/project/Glog/service/GitHubService.java
  server/src/main/java/com/project/Glog/service/GuestbookService.java
  server/src/main/java/com/project/Glog/service/HistoryService.java
  server/src/main/java/com/project/Glog/service/PathService.java
  server/src/main/java/com/project/Glog/service/PostService.java
  server/src/main/java/com/project/Glog/service/PrPostService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
  server/src/main/java/com/project/Glog/service/ScrapService.java
  server/src/main/java/com/project/Glog/service/TemplateService.java
  server/src/main/java/com/project/Glog/service/TemporaryService.java
  server/src/main/java/com/project/Glog/service/VisitService.java
Labels: 종경, 백엔드, refactor

#185 #183시큐리티 관련 의존성 변경
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
  server/src/main/java/com/project/Glog/security/TokenAuthenticationFilter.java
  server/src/main/java/com/project/Glog/security/oauth2/CustomOAuth2UserService.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationFailureHandler.java
  server/src/main/java/com/project/Glog/security/oauth2/OAuth2AuthenticationSuccessHandler.java
Labels: 종경, 백엔드, refactor

#187 회원 탈퇴 로직 추가
  server/src/main/java/com/project/Glog/controller/UserController.java
  server/src/main/java/com/project/Glog/repository/UserRepository.java
  server/src/main/java/com/project/Glog/security/CustomUserDetailsService.java
Labels: 종경, 백엔드, feature

#188 entity 수정
  server/src/main/java/com/project/Glog/domain/Category.java
  server/src/main/java/com/project/Glog/domain/GithubRepository.java
  server/src/main/java/com/project/Glog/domain/Post.java
  server/src/main/java/com/project/Glog/domain/PrPost.java
  server/src/main/java/com/project/Glog/domain/User.java
Labels: 종경, 백엔드, modify

#192 Feature/#191 리팩토링
  .gitignore
  server/src/main/java/com/project/Glog/config/SecurityConfig.java
  server/src/main/java/com/project/Glog/domain/Alarm.java
  server/src/main/java/com/project/Glog/dto/AlarmDto.java
  server/src/main/java/com/project/Glog/service/FriendService.java
  server/src/main/java/com/project/Glog/service/ReplyService.java
  server/src/main/resources/application.properties
Labels: 두영, fix, 백엔드
